### ISSUE TITLE
Add blog images and post authors

### ISSUE THREAD

**Issue by Peter-holyoke** [ProvidenceGeeks/website-lambda-wordpress#10]
## Type of Change
- [x] New Feature Request
- [ ] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary

New Feature Request / Improvement:
- Description: Update wordpress lambda function to return blog image and the name of the user who posted.
- Acceptance Criteria:
    1. Data should contain an array of images for each blog post which contains a thumbnail, medium, large and full-sized image
    1. Data should contain an additional field called "author_name" which contains the full name of the user who posted the blog post

**Comment by thescientist13** [comment]
`author_name` and `media_details` are now part of an individual blog post item
https://s3.amazonaws.com/data.pvdgeeks.org/wordpress/wordpress-data.json
