### ISSUE TITLE
Integration with WordPress API

### ISSUE THREAD

**Issue by saimatsumoto** [ProvidenceGeeks/website-lambda-wordpress#5]
## Type of Change
- [x] New Feature Request
- [ ] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary
New Feature Request / Improvement:

* Description: Consume data from PVD Geeks WordPress through a Lambda function
* Docs: https://github.com/ProvidenceGeeks/website-docs/wiki/External-Service:-WordPress 
* Dependencies: Integration with WordPress to be a data source for the Posts API - https://github.com/ProvidenceGeeks/website-lambda-wordpress/issues/7
* Acceptance Criteria:
    1. Should query WordPress API and pull posts data from the service - @Peter-holyoke 
    1.  Data pulled from the API should be against the defined affiliates list and should be defined as an array in src/index.js - @Peter-holyoke 
    1.  The data should be saved in the same S3 bucket with the filename _wordpress-data.json_ (for local testing and until S3 bucket is setup, it can just write the file to an "output" directory locally (directory should be added to .gitignore) - @thescientist13
    1. This should configured to run at a scheduled interval (every 24h?) - @thescientist13

**Comment by saimatsumoto** [comment]
@thescientist13 please update accordingly, thank you!

**Comment by thescientist13** [comment]
1. Wordpress Lambda: https://s3.amazonaws.com/lambda.pvdgeeks.org/wordpress-0.1.0.zip
2. Wordpress Data: https://s3.amazonaws.com/data.pvdgeeks.org/wordpress/wordpress-data.json
